repos:
- repo: local
  hooks:
    - id: formatter
      name: Run Black formatter
      entry: bash -c 'poe format'
      language: system

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
